from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("КАСТОМАЙЗЕР")
        MainWindow.resize(845, 667)
        MainWindow.setStyleSheet("background-color: rgb(151, 151, 151);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fram_1 = QtWidgets.QFrame(self.centralwidget)
        self.fram_1.setGeometry(QtCore.QRect(10, 10, 510, 651))
        self.fram_1.setStyleSheet("QFrame { border: 2px solid white; }\n"
"QPushButton:hover {\n"
"    border: 2px solid #5DADE2; /* Или любой другой цвет */\n"
"}\n"
"QPushButton:focus {\n"
"    border: 2px solid #5DADE2; /* Подсветка границы при фокусе */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid #5DADE2; /* Или любой другой цвет */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #5DADE2; /* Подсветка границы при фокусе */\n"
"}")
        self.fram_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fram_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fram_1.setObjectName("fram_1")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.fram_1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 491, 635))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.t_label_1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.t_label_1.setFont(font)
        self.t_label_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label_1.setObjectName("t_label_1")
        self.verticalLayout_3.addWidget(self.t_label_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_coordinate_sistem = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_coordinate_sistem.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_coordinate_sistem.setObjectName("lbl_coordinate_sistem")
        self.verticalLayout_2.addWidget(self.lbl_coordinate_sistem)
        self.lbl_x = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_x.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_x.setObjectName("lbl_x")
        self.verticalLayout_2.addWidget(self.lbl_x)
        self.lbl_y = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_y.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_y.setObjectName("lbl_y")
        self.verticalLayout_2.addWidget(self.lbl_y)
        self.lbl_z = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_z.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_z.setObjectName("lbl_z")
        self.verticalLayout_2.addWidget(self.lbl_z)
        self.lbl_vx = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_vx.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_vx.setObjectName("lbl_vx")
        self.verticalLayout_2.addWidget(self.lbl_vx)
        self.lbl_vy = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_vy.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_vy.setObjectName("lbl_vy")
        self.verticalLayout_2.addWidget(self.lbl_vy)
        self.lbl_vz = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_vz.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_vz.setObjectName("lbl_vz")
        self.verticalLayout_2.addWidget(self.lbl_vz)
        self.lbl_t0 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_t0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_t0.setObjectName("lbl_t0")
        self.verticalLayout_2.addWidget(self.lbl_t0)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_coordinat_sistem = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_coordinat_sistem.setObjectName("comboBox_coordinat_sistem")
        self.comboBox_coordinat_sistem.addItem("")
        self.comboBox_coordinat_sistem.addItem("")
        self.comboBox_coordinat_sistem.addItem("")
        self.verticalLayout.addWidget(self.comboBox_coordinat_sistem)
        self.lineEdit_x = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.verticalLayout.addWidget(self.lineEdit_x)
        self.lineEdit_y = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.verticalLayout.addWidget(self.lineEdit_y)
        self.lineEdit_z = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_z.setObjectName("lineEdit_z")
        self.verticalLayout.addWidget(self.lineEdit_z)
        self.lineEdit_vx = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_vx.setObjectName("lineEdit_vx")
        self.verticalLayout.addWidget(self.lineEdit_vx)
        self.lineEdit_vy = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_vy.setObjectName("lineEdit_vy")
        self.verticalLayout.addWidget(self.lineEdit_vy)
        self.lineEdit_vz = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_vz.setObjectName("lineEdit_vz")
        self.verticalLayout.addWidget(self.lineEdit_vz)
        self.lineEdit_t0 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_t0.setObjectName("lineEdit_t0")
        self.verticalLayout.addWidget(self.lineEdit_t0)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.t_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t_label_2.setFont(font)
        self.t_label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label_2.setObjectName("t_label_2")
        self.verticalLayout_3.addWidget(self.t_label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lbl_dt_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_dt_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_dt_3.setObjectName("lbl_dt_3")
        self.verticalLayout_12.addWidget(self.lbl_dt_3)
        self.lbl_H_k_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_H_k_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_H_k_5.setObjectName("lbl_H_k_5")
        self.verticalLayout_12.addWidget(self.lbl_H_k_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.comboBox_grav_model = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_grav_model.setObjectName("comboBox_grav_model")
        self.comboBox_grav_model.addItem("")
        self.comboBox_grav_model.addItem("")
        self.comboBox_grav_model.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_grav_model)
        self.comboBox_atmo_model = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_atmo_model.setObjectName("comboBox_atmo_model")
        self.comboBox_atmo_model.addItem("")
        self.comboBox_atmo_model.addItem("")
        self.comboBox_atmo_model.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_atmo_model)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.t_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t_label_3.setFont(font)
        self.t_label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label_3.setObjectName("t_label_3")
        self.verticalLayout_3.addWidget(self.t_label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_dt = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_dt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_dt.setObjectName("lbl_dt")
        self.verticalLayout_4.addWidget(self.lbl_dt)
        self.lbl_H_k_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_H_k_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_H_k_2.setObjectName("lbl_H_k_2")
        self.verticalLayout_4.addWidget(self.lbl_H_k_2)
        self.lbl_H_k = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_H_k.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_H_k.setObjectName("lbl_H_k")
        self.verticalLayout_4.addWidget(self.lbl_H_k)
        self.lbl_epsilon = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_epsilon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_epsilon.setObjectName("lbl_epsilon")
        self.verticalLayout_4.addWidget(self.lbl_epsilon)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_dt = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_dt.setObjectName("lineEdit_dt")
        self.verticalLayout_5.addWidget(self.lineEdit_dt)
        self.lineEdit_H_ch_dt = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_H_ch_dt.setObjectName("lineEdit_H_ch_dt")
        self.verticalLayout_5.addWidget(self.lineEdit_H_ch_dt)
        self.lineEdit_H_k = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_H_k.setObjectName("lineEdit_H_k")
        self.verticalLayout_5.addWidget(self.lineEdit_H_k)
        self.lineEdit_epsilon = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_epsilon.setObjectName("lineEdit_epsilon")
        self.verticalLayout_5.addWidget(self.lineEdit_epsilon)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.t_label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t_label_4.setFont(font)
        self.t_label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label_4.setObjectName("t_label_4")
        self.verticalLayout_3.addWidget(self.t_label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_phi = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_phi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_phi.setObjectName("lbl_phi")
        self.verticalLayout_6.addWidget(self.lbl_phi)
        self.lbl_lambda = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_lambda.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lambda.setObjectName("lbl_lambda")
        self.verticalLayout_6.addWidget(self.lbl_lambda)
        self.lbl_epsilon_p = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_epsilon_p.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_epsilon_p.setObjectName("lbl_epsilon_p")
        self.verticalLayout_6.addWidget(self.lbl_epsilon_p)
        self.lbl_stride = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_stride.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_stride.setObjectName("lbl_stride")
        self.verticalLayout_6.addWidget(self.lbl_stride)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_phi = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_phi.setObjectName("lineEdit_phi")
        self.verticalLayout_7.addWidget(self.lineEdit_phi)
        self.lineEdit_lambda = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_lambda.setObjectName("lineEdit_lambda")
        self.verticalLayout_7.addWidget(self.lineEdit_lambda)
        self.lineEdit_epsilon_p = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_epsilon_p.setObjectName("lineEdit_epsilon_p")
        self.verticalLayout_7.addWidget(self.lineEdit_epsilon_p)
        self.lineEdit_stride = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_stride.setObjectName("lineEdit_stride")
        self.verticalLayout_7.addWidget(self.lineEdit_stride)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(525, 10, 310, 651))
        self.frame_2.setStyleSheet("QFrame { border: 2px solid white; }\n"
"QPushButton:hover {\n"
"    border: 2px solid #5DADE2; /* Или любой другой цвет */\n"
"}\n"
"QPushButton:focus {\n"
"    border: 2px solid #5DADE2; /* Подсветка границы при фокусе */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid #5DADE2; /* Или любой другой цвет */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #5DADE2; /* Подсветка границы при фокусе */\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 294, 170))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_load_default = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_load_default.setFont(font)
        self.btn_load_default.setObjectName("btn_load_default")
        self.verticalLayout_10.addWidget(self.btn_load_default)
        self.btn_load_file = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_load_file.setFont(font)
        self.btn_load_file.setObjectName("btn_load_file")
        self.verticalLayout_10.addWidget(self.btn_load_file)
        self.btn_load_last = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_load_last.setFont(font)
        self.btn_load_last.setObjectName("btn_load_last")
        self.verticalLayout_10.addWidget(self.btn_load_last)
        self.btn_start = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_10.addWidget(self.btn_start)
        self.btn_save_and_annotate = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_and_annotate.setFont(font)
        self.btn_save_and_annotate.setObjectName("btn_save_and_annotate")
        self.verticalLayout_10.addWidget(self.btn_save_and_annotate)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 190, 291, 451))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_7)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_11.addWidget(self.progressBar)
        self.logger = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.logger.setFont(font)
        self.logger.setObjectName("logger")
        self.verticalLayout_11.addWidget(self.logger)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.t_label_1.setText(_translate("MainWindow", "НАЧАЛЬНЫЕ КООРДИНАТЫ И СКОРОСТИ"))
        self.lbl_coordinate_sistem.setText(_translate("MainWindow", "СИСТМЕМА КООРДИНАТ"))
        self.lbl_x.setText(_translate("MainWindow", "X"))
        self.lbl_y.setText(_translate("MainWindow", "Y"))
        self.lbl_z.setText(_translate("MainWindow", "Z"))
        self.lbl_vx.setText(_translate("MainWindow", "Vx"))
        self.lbl_vy.setText(_translate("MainWindow", "Vy"))
        self.lbl_vz.setText(_translate("MainWindow", "Vz"))
        self.lbl_t0.setText(_translate("MainWindow", "t0"))
        self.comboBox_coordinat_sistem.setItemText(0, _translate("MainWindow", "СТАРТОВАЯ ИНЕРЦИАЛЬНАЯ"))
        self.comboBox_coordinat_sistem.setItemText(1, _translate("MainWindow", "ЭКВАТОРИАЛЬНАЯ ГЕОЦЕНТРИЧЕСКАЯ ИНЕРЦИАЛЬНАЯ"))
        self.comboBox_coordinat_sistem.setItemText(2, _translate("MainWindow", "ГРИНВИЧСКАЯ"))
        self.t_label_2.setText(_translate("MainWindow", "ПАРАМЕТРЫ МОДЕЛЕЙ"))
        self.lbl_dt_3.setText(_translate("MainWindow", "МОДЕЛЬ ГРАВИТАЦИОННОГО ПОЛЯ"))
        self.lbl_H_k_5.setText(_translate("MainWindow", "МОДЕЛЬ АТМОСФЕРЫ"))
        self.comboBox_grav_model.setItemText(0, _translate("MainWindow", "ЦЕНТРАЛЬНОЕ"))
        self.comboBox_grav_model.setItemText(1, _translate("MainWindow", "-"))
        self.comboBox_grav_model.setItemText(2, _translate("MainWindow", "-"))
        self.comboBox_atmo_model.setItemText(0, _translate("MainWindow", "БЕЗ АТМОСФЕРЫ"))
        self.comboBox_atmo_model.setItemText(1, _translate("MainWindow", "СТАНДАРТНАЯ АТМОСФЕРА"))
        self.comboBox_atmo_model.setItemText(2, _translate("MainWindow", "ГЛОБАЛЬНАЯ АТМОСФЕРА"))
        self.t_label_3.setText(_translate("MainWindow", "ПАРАМЕТРЫ ДЛЯ ВЫЧИСЛЕНИЙ"))
        self.lbl_dt.setText(_translate("MainWindow", "ШАГ ДЛЯ РК4 (dt), с"))
        self.lbl_H_k_2.setText(_translate("MainWindow", "ВЫСОТА СМЕНЫ ШАГА ДЛЯ ТОЧНОСТИ, м"))
        self.lbl_H_k.setText(_translate("MainWindow", "МИНИМАЛЬНАЯ ВЫСОТА (H_k), м"))
        self.lbl_epsilon.setText(_translate("MainWindow", "ДОПУСТИМАЯ ПОГРЕШНОСТЬ ПО ВЫСОТЕ (ε), м"))
        self.t_label_4.setText(_translate("MainWindow", "ПАРАМЕТРЫ ДЛЯ ПОСТРОЕНИЯ ВИЗУАЛИЗАЦИИ"))
        self.lbl_phi.setText(_translate("MainWindow", "КОЛ-ВО ПРОМЕЖ. ЗНАЧЕНИЙ УГЛА φ (ШИРОТА)"))
        self.lbl_lambda.setText(_translate("MainWindow", "КОЛ-ВО ПРОМЕЖ. ЗНАЧЕНИЙ УГЛА λ (ДОЛГОТА)"))
        self.lbl_epsilon_p.setText(_translate("MainWindow", "ДОПУСТИМАЯ ПОГРЕШНОСТЬ ОПРЕДЕЛЕНИЯ ПРОЕКЦИИ (ε_p), м"))
        self.lbl_stride.setText(_translate("MainWindow", "ВЕЛИЧИНА ШАГА СЕТКИ ПОСТРОЕНИЯ"))
        self.btn_load_default.setText(_translate("MainWindow", "ЗАГРУЗИТЬ СТАНДАРТНЫЕ ПАРАМЕТРЫ"))
        self.btn_load_file.setText(_translate("MainWindow", "ЗАГРУЗИТЬ ПАРАМЕТРЫ ИЗ ФАЙЛА"))
        self.btn_load_last.setText(_translate("MainWindow", "ЗАГРУЗИТЬ ПОСЛЕДНИЕ ПАРАМЕТРЫ"))
        self.btn_start.setText(_translate("MainWindow", "ЗАПУСК РАСЧЕТОВ"))
        self.btn_save_and_annotate.setText(_translate("MainWindow", "СОХРАНИТЬ И АННОТИРОВАТЬ РЕЗУЛЬТАТЫ"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())